### PR TITLE
Fix PATH used for running binaries

### LINKED ISSUE #2: VirtualBox not correctly detected

### PR DESCRIPTION
**Pull request by rmccue**
Fixes #2.

### CODE REVIEW

**Review by BronsonQuick — APPROVED** [review]

**Comment by jonathan-dejong** [comment]
Awesome :) 
Will you put out an updated .dmg? I just downloaded chassis desktop 0.2.0 Beta build and was running into the same issue as everyone else. Would love to test this out today!

**Comment by rmccue** [comment]
@jonathan-dejong Will definitely publish an updated binary, likely not today though :)

**Comment by BronsonQuick** [comment]
@jonathan-dejong Hopefully the new binary will fix this for you: https://github.com/Chassis/Desktop/releases/tag/0.2.1 Sorry for the delay on publishing it! WordCamp Europe kept us all pretty busy!

**Comment by stuartshields** [comment]
@BronsonQuick confirmed the new dmg file resolves the issue.

**Comment by jonathan-dejong** [comment]
@BronsonQuick same! Well done!

**Comment by jonathan-dejong** [comment]
Sorry to be the bearer of bad news but it seems PATH is still an issue (possibly).
The initial installer works as expected now and I can create a new chassis box as excepted. However when attempting to Launch the box somewhat same error appears.

I can't copy the whole output since there's no copying the output window and I cant screenshot it since it resets scroll position as soon as I "leave" the application.

But here it is in short:
`
vagrant up
No usable default provider could be found for your system
`
And then a whole section about 3rd party systems, vagrant etc. and ending in 
`(Exited with error code 1)`

Should mention that I updated both vagrant and virtualbox just a few days ago so I'm running the latest (almost, think virtualbox has a new minor release).

**Comment by rmccue** [comment]
@jonathan-dejong Thanks for the update; I can replicate now again, will fix ASAP.

**Pull request merged**
